# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Run bash script
        run: |
          chmod +x linux.sh
          ./linux.sh
          tree

      - uses: actions/upload-artifact@v4
        with:
          name: bin
          path: telegram-bot-api/bin
        
  # This workflow contains a single job called "build"
  build-win:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Run script
        shell: pwsh
        run: .\windows.ps1
          
   
      - uses: actions/upload-artifact@v4
        with:
          name: bin
          path: telegram-bot-api/bin/telegram-bot-api # or path/to/artifact
