name: Build Local Bot Server

on:
  push:
  workflow_dispatch:

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run bash script
        run: |
          chmod +x linux.sh
          ./linux.sh
      - uses: actions/upload-artifact@v4
        with:
          name: linux-bin
          path: telegram-bot-api/bin
        
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        shell: pwsh
        run: .\windows.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: windows-bin
          path: telegram-bot-api/bin
          
   
      - uses: actions/upload-artifact@v4
        with:
          name: bin
          path: telegram-bot-api/bin/telegram-bot-api # or path/to/artifact
